### ISSUE TITLE
Hydrojetting to clean out sewer lines in garage

### ISSUE THREAD

**Issue by jfriesne** [jfriesne/parkwood_hoa#10]
Jane wrote:

> I ran into Danny this afternoon. We talked about Valerie's and unit 10's problem. I asked him to contact Chris from CR for quotes for hydrojeting those two stacks. He said he would call Chris then and ask for the same. I told him it was OK if Chris gave Alex a verbal quote for the work. But that we were still owed the report on what Chris found and did in unit 10 and asked that Danny request that as well.
> 
> We probably do need to get two more bids, I would like to see them from Merry and F&M.
> Can we get this done quickly? Before any more damage occurs?
> 
> Thanks
> Jane
>

**Comment by jfriesne** [comment]
Chris the plumber quoted us $2500 to hydrojet all the drains in the garage.

**Comment by AlanaEllis** [comment]
I saw a CR Plumbing invoice come in for $480 for cleaning all the drains in unit 6 down into the garage lines, 25 feet.

**Comment by AlanaEllis** [comment]
Merry Plumbing bid: $1,778 PLUS Additional Cost for Unit #10 & #6, $860 = $2,638

**Comment by AlanaEllis** [comment]
F&M BID: $3,200-3,500 [DOES NOT INCLUDE ANY SPECIAL REPAIRS OF Unit #10 & #6]

**Comment by jfriesne** [comment]
The hydrojetting was performed on July 30th, so this issue is resolved (for now)
