### ISSUE TITLE
Water heater return line needs refurbishment

### ISSUE THREAD

**Issue by jfriesne** [jfriesne/parkwood_hoa#15]
Bateman reports that our water heater's return line is in need of repair ASAP, or else it is likely to fail in the near-to-medium future -- see attached screenshot from their recent invoice.

<img width="1568" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/1404232/134717995-28cd2c28-998f-40a4-9cf5-4c1583fb8963.png">

**Comment by jfriesne** [comment]
Attached is Bateman's bid for repairs to the hot water return line.

[Bateman-OakKnollAv.500S.PipingPmpMtrInsul(2) (2) (2).pdf](https://github.com/jfriesne/parkwood_hoa/files/7227759/Bateman-OakKnollAv.500S.PipingPmpMtrInsul.2.2.2.pdf)

**Comment by CYBERIANCYBERNAUT** [comment]
Jeremy,
 
Maybe we should do the repairs that Bateman recommends, then next year get the new higher efficiency hot water equipment.
 
If we didn't have such large expenses this year, I would recommend getting the new equipment now.
 
Tom
 
 
-----Original Message-----

**Comment by jfriesne** [comment]
I think doing the recommended repairs is a good idea regardless of our long-term plans.

Jeremy

**Comment by CYBERIANCYBERNAUT** [comment]
I agree. The bottom line of the proposal is:
 
  Hot Water Equipment Repairs $1,544.00
  Piping Insulation $720.00
 
The total cost would be $2,264.00.
 
I recommend that we go forward with these repairs.
 
Tom
 
-----Original Message-----

**Comment by CYBERIANCYBERNAUT** [comment]
Do we want to get a quote from Bateman for the new hot water service before we decide this?
 
That being said, I agree with these repairs, as they make sense and some of it will still be in use when we get the new machine.
-----Original Message-----
From: 
Sent: Sep 24, 2021 1:00 PM
To: jfriesne/parkwood_hoa , jfriesne/parkwood_hoa 
Cc: PARKWOOD HOA 
Subject: {Parkwood HOA Board} Re: [jfriesne/parkwood_hoa] Water heater return line needs refurbishment (#15)

I agree. The bottom line of the proposal is:
 
  Hot Water Equipment Repairs $1,544.00
  Piping Insulation $720.00
 
The total cost would be $2,264.00.
 
I recommend that we go forward with these repairs.
 
Tom
 

-----Original Message-----

**Comment by jfriesne** [comment]
This task has been completed.
