### ISSUE TITLE
Reschedule gardeners to do the weekly gardening *before* the building cleaners clean, rather than just after

### ISSUE THREAD

**Issue by parkwood-hoa** [jfriesne/parkwood_hoa#7]
Debb reports that the gardeners come and do the gardening work on Friday afternoons, which is just a few hours after the cleaners come and sweep the walkways on Friday mornings.

This is sub-optimal, because the gardeners tend to blow pine needles and other debris onto the walkways, partially undoing the cleaner's work and leaving the walkways untidy for the rest of the week.

In order to keep the walkways cleaner, it would be good if the gardeners could be rescheduled to Thursday, so that the gardening happens *before* the cleaners sweep the walkways.

**Comment by jfriesne** [comment]
Closing (obsolete issue)
